### PR TITLE
Minor styling changes to footer

### PR DESCRIPTION
**Pull request by AgrimArsh**
Defined a concrete height to the footer, added background color to be `rgb(77,13,11)` and text color as white. Please see to it once, need some advise from the design team though regarding the colors.

### CODE REVIEW

**Comment by epelaaez** [comment]
image
 
Is this how it is supposed to look like?

**Comment by AgrimArsh** [comment]
Yep, more or less, just need to add a bit of `padding-top`.

**Comment by epelaaez** [comment]
Can you add some changes to the overall look rather than just the footer? I think that pushing the pull request in its current form would cause the style of the website to look somewhat inconsistent.

**Comment by AgrimArsh** [comment]
Added formatting changes to the Header similar to that of the footer, as told by you. Just check once, thanks!

**Comment by epelaaez** [comment]
Can you attach a screenshot of the changes you made here?

**Comment by epelaaez** [comment]
This is now irrelevant since the gh-pages branch is soon-to-be deprecated

**Pull request closed without merging**
